### PR TITLE
Add some rotating default colors for @ARGV patterns

### PR DESCRIPTION
**Pull request by scottchiefbaker**
Instead of using bold red for every pattern, rotate through some default colors. Borrowed the idea from "h"

https://github.com/paoloantinori/hhighlighter
https://asciinema.org/a/5cbw3rnhchsdnxcihtusf48vp

### CODE REVIEW

**Comment by goodell** [comment]
I like the feature idea.  It looks like the implementation makes the existing `--color` arguments non-functional though?  I'm busy this weekend and don't have time to play with this, but I'll try to find a little time this week.

**Comment by scottchiefbaker** [comment]
Any update on this? What needs to be done to make this happen?

**Comment by goodell** [comment]
Well... at a minimum it should pass [the tests in the `t/` directory](https://github.com/goodell/highlight/tree/master/t).  Right now, it fails the very first test:

```
DGOODELL-M-J06E ~/d/g/g/h/t git:master ❯❯❯ git checkout scottchiefbaker/master
Note: checking out 'scottchiefbaker/master'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

HEAD is now at 05a1d20... Merge branch 'master' of github.com:goodell/highlight

DGOODELL-M-J06E ~/d/g/g/h/t git:remotes/scottchiefbaker/master ❯❯❯ ./runtests
testing tc0
Cannot pass --filter options AND regular options at the same time
Files tc0.expected and tc0.out differ
Usage: ../highlight [-i] [--color=COLOR_STRING] [--] <PATTERN0> [PATTERN1...]
  or
Usage: ../highlight [-i] [--filter COLOR,PATTERN] [--filter COLOR,PATTERN] ...

This is highlight version 1.2.

This program takes text via standard input and outputs it with the given
perlre(1) pattern(s) highlighted with the given color.  If no color option
is specified, it defaults to 'bold red'.  Colors may be anything
that Perl's Term::ANSIColor understands.  This program is similar to
"grep --color PATTERN" except both matching and non-matching lines are
printed.

The default color can be selected via the $HIGHLIGHT_COLOR environment
variable.  The command-line option takes precedence.

Passing -i or --ignore-case will enable case-insensitive matching.

If your pattern begins with a dash ('-'), you can pass a '--' argument
after any options and before your pattern to distinguish it from an
option.

Cannot pass --filter options AND regular options at the same time
```

I should probably throw the project up on Travis CI, but it's not exactly a project with a high rate of change.

**Comment by goodell** [comment]
I've [added highlight to Travis CI](https://travis-ci.org/goodell/highlight).  This PR doesn't have a CI badge on it for some reason, probably because it was opened before I enabled Travis.  Perhaps a subsequent update to the PR commits by you would trigger Travis?

**Comment by scottchiefbaker** [comment]
I had no idea there were tests! My bad. I'll investigate more and get back to you.

**Comment by goodell** [comment]
Hi Scott, this PR's been open for a long time and hasn't been merged for a whole bunch of reasons:

1. It doesn't merge cleanly (conflict on `README.md`), despite me not touching the master branch since mid-2016.
2. It seems like it doesn't pass the unit tests in Travis: https://travis-ci.org/goodell/highlight/builds/569076336
3. The Travis results don't appear in the Github UI, probably because this PR predates adding Travis support.
4. The PR has a _lot_ of changes all bundled up into one big "take it or leave it" batch.
5. Lots of changes are pretty unnecessary/undesirable if you're actually trying to contribute back to an upstream project, such as reindenting everything with hard tabs (yuck!). It also noticeably changes the CLI arguments/behavior, so it kind of messes with other scripts that are built on top of the existing behavior.

Seems like it might be best to just keep this all off as a fork for now. If you do still want me to take some of this functionality upstream, please open new PRs with logical groupings of commits so we can merge them incrementally instead of as a big bang.

**Pull request closed without merging**
